"""Solo self-play: actor-critic on final score against the dice RNG.

Games are generated by sampling the current policy. Returns are Monte Carlo
``total_score / SCORE_SCALE``. Optional KL penalty to the init (BC) checkpoint
slows forgetting. Best checkpoint is kept by greedy eval score, not train loss.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from doppelt.core.phases import Phase
from doppelt.core.scoring import total_score
from doppelt.engine.game import apply_action, legal_action_ids, new_game
from doppelt.ml.encoding import SCORE_SCALE, encode_state
from doppelt.ml.eval import eval_policy_scores
from doppelt.ml.model import (
    DEFAULT_ARCHITECTURE,
    DEFAULT_HIDDEN,
    build_net,
    load_checkpoint,
    require_torch,
    save_checkpoint,
)
from doppelt.ml.policy import NeuralPolicy


@dataclass(frozen=True)
class SelfPlayResult:
    checkpoint_path: Path
    iterations: int
    best_eval_score: float
    last_mean_score: float
    last_policy_loss: float
    games: int


@dataclass
class _Episode:
    features: list[tuple[float, ...]]
    masks: list[tuple[bool, ...]]
    actions: list[int]
    score: float
    terminal: bool


def _masked_log_probs(logits, mask, torch, F):
    """Log-softmax that is 0 on illegal actions (avoids 0 * -inf NaNs)."""
    log_probs = F.log_softmax(logits, dim=-1)
    return torch.where(mask, log_probs, torch.zeros_like(log_probs))


def collect_episode(
    net,
    seed: int,
    *,
    max_actions: int = 5_000,
    device: str = "cpu",
) -> _Episode:
    """Play one sampled game; labels are the actions the net actually took."""
    torch, _nn, _F = require_torch()
    state = new_game(seed=seed)
    generator = torch.Generator(device="cpu")
    generator.manual_seed(int(seed) ^ 0x51A7_E11)
    net.eval()
    features: list[tuple[float, ...]] = []
    masks: list[tuple[bool, ...]] = []
    actions: list[int] = []
    for _ in range(max_actions):
        if state.phase is Phase.GAME_OVER:
            break
        legal = legal_action_ids(state)
        if not legal:
            break
        encoded = encode_state(state, legal)
        feat = torch.tensor([encoded.features], dtype=torch.float32, device=device)
        mask = torch.tensor([encoded.mask], dtype=torch.bool, device=device)
        with torch.no_grad():
            logits, _value = net(feat, mask)
        probs = torch.softmax(logits.cpu(), dim=-1)
        action_id = int(torch.multinomial(probs, 1, generator=generator).item())
        if action_id not in legal:
            action_id = legal[0]
        features.append(encoded.features)
        masks.append(encoded.mask)
        actions.append(action_id)
        apply_action(state, action_id, check_legal=False)
    return _Episode(
        features=features,
        masks=masks,
        actions=actions,
        score=float(total_score(state.sheet)),
        terminal=state.phase is Phase.GAME_OVER,
    )


def _batch_from_episodes(episodes: list[_Episode], torch, score_scale: float):
    features: list[tuple[float, ...]] = []
    masks: list[tuple[bool, ...]] = []
    actions: list[int] = []
    returns: list[float] = []
    for episode in episodes:
        scaled = episode.score / score_scale
        features.extend(episode.features)
        masks.extend(episode.masks)
        actions.extend(episode.actions)
        returns.extend([scaled] * len(episode.actions))
    return (
        torch.tensor(features, dtype=torch.float32),
        torch.tensor(masks, dtype=torch.bool),
        torch.tensor(actions, dtype=torch.long),
        torch.tensor(returns, dtype=torch.float32),
    )


def _actor_critic_loss(
    net,
    features,
    mask,
    actions,
    returns,
    *,
    torch,
    F,
    value_coef: float,
    entropy_coef: float,
    kl_coef: float,
    freeze_net,
):
    logits, values = net(features, mask)
    log_probs = _masked_log_probs(logits, mask, torch, F)
    chosen = log_probs.gather(1, actions.unsqueeze(1)).squeeze(1)
    advantage = (returns - values.detach())
    if advantage.numel() > 1:
        std = advantage.std()
        if float(std) > 1e-6:
            advantage = (advantage - advantage.mean()) / (std + 1e-8)
    policy_loss = -(chosen * advantage).mean()
    value_loss = F.mse_loss(values, returns)
    probs = torch.where(mask, log_probs.exp(), torch.zeros_like(log_probs))
    entropy = -(probs * log_probs).sum(dim=-1).mean()
    loss = policy_loss + value_coef * value_loss - entropy_coef * entropy
    if freeze_net is not None and kl_coef > 0:
        with torch.no_grad():
            freeze_logits, _ = freeze_net(features, mask)
            freeze_log = _masked_log_probs(freeze_logits, mask, torch, F)
        kl = (probs * (log_probs - freeze_log)).sum(dim=-1).mean()
        loss = loss + kl_coef * kl
    return loss, float(policy_loss.item()), float(value_loss.item()), float(entropy.item())


def train_selfplay(
    *,
    out_path: Path,
    init_checkpoint: Path | None = None,
    iterations: int = 20,
    games_per_iter: int = 16,
    seed: int = 0,
    lr: float = 3e-4,
    value_coef: float = 0.5,
    entropy_coef: float = 0.01,
    kl_coef: float = 0.0,
    max_actions: int = 5_000,
    eval_games: int = 8,
    eval_seed: int = 20_000,
    eval_every: int = 5,
    hidden: int = DEFAULT_HIDDEN,
    architecture: str = DEFAULT_ARCHITECTURE,
    on_progress: Callable[[str], None] | None = None,
) -> SelfPlayResult:
    """A2C self-play starting from a BC checkpoint (or a random net)."""
    if iterations < 1:
        raise ValueError("iterations must be at least 1")
    if games_per_iter < 1:
        raise ValueError("games_per_iter must be at least 1")
    torch, _nn, F = require_torch()
    torch.manual_seed(seed)

    freeze_net = None
    score_scale = SCORE_SCALE
    if init_checkpoint is not None:
        net, payload = load_checkpoint(init_checkpoint)
        hidden = int(payload.get("hidden", hidden))
        architecture = getattr(net, "architecture", str(payload.get("architecture", "mlp")))
        score_scale = float(payload.get("score_scale", SCORE_SCALE))
        if kl_coef > 0:
            freeze_net, _ = load_checkpoint(init_checkpoint)
            freeze_net.eval()
            for param in freeze_net.parameters():
                param.requires_grad_(False)
    else:
        net = build_net(hidden=hidden, architecture=architecture)
        payload = {}

    optimizer = torch.optim.Adam(net.parameters(), lr=lr)
    best_eval = float("-inf")
    last_mean = 0.0
    last_policy_loss = 0.0
    total_games = 0

    def log(message: str) -> None:
        if on_progress is not None:
            on_progress(message)

    def maybe_eval(iteration: int, force: bool = False) -> float | None:
        nonlocal best_eval
        if eval_games < 1:
            return None
        if not force and iteration % eval_every != 0 and iteration != iterations:
            return None
        policy = NeuralPolicy(net=net, payload=payload, seed=eval_seed, sample=False)
        row, _failures = eval_policy_scores(
            policy,
            games=eval_games,
            seed_start=eval_seed,
            max_actions=max_actions,
            collect_failures=False,
        )
        if row.mean_score >= best_eval:
            best_eval = row.mean_score
            save_checkpoint(
                out_path,
                net,
                hidden=hidden,
                architecture=architecture,
                extra={
                    "score_scale": score_scale,
                    "iteration": iteration,
                    "eval_score": row.mean_score,
                    "selfplay_mean": last_mean,
                },
            )
        log(f"iter {iteration}: greedy eval mean={row.mean_score:.1f} (best={best_eval:.1f})")
        return row.mean_score

    maybe_eval(0, force=True)

    for iteration in range(1, iterations + 1):
        episodes = [
            collect_episode(
                net,
                seed + total_games + index,
                max_actions=max_actions,
            )
            for index in range(games_per_iter)
        ]
        total_games += games_per_iter
        last_mean = sum(ep.score for ep in episodes) / games_per_iter
        unfinished = sum(1 for ep in episodes if not ep.terminal)
        features, mask, actions, returns = _batch_from_episodes(episodes, torch, score_scale)
        if features.size(0) == 0:
            raise RuntimeError("self-play collected no actions")
        net.train()
        loss, last_policy_loss, value_loss, entropy = _actor_critic_loss(
            net,
            features,
            mask,
            actions,
            returns,
            torch=torch,
            F=F,
            value_coef=value_coef,
            entropy_coef=entropy_coef,
            kl_coef=kl_coef,
            freeze_net=freeze_net,
        )
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(net.parameters(), 1.0)
        optimizer.step()
        log(
            f"iter {iteration}/{iterations}: play_mean={last_mean:.1f} "
            f"policy={last_policy_loss:.4f} value={value_loss:.4f} "
            f"entropy={entropy:.3f} unfinished={unfinished}"
        )
        maybe_eval(iteration)

    if best_eval == float("-inf"):
        save_checkpoint(
            out_path,
            net,
            hidden=hidden,
            architecture=architecture,
            extra={"score_scale": score_scale, "iteration": iterations, "selfplay_mean": last_mean},
        )
        best_eval = last_mean

    return SelfPlayResult(
        checkpoint_path=Path(out_path),
        iterations=iterations,
        best_eval_score=best_eval,
        last_mean_score=last_mean,
        last_policy_loss=last_policy_loss,
        games=total_games,
    )


def format_selfplay_result(result: SelfPlayResult) -> str:
    return (
        f"self-play: {result.games} games, {result.iterations} iters, "
        f"last_play_mean={result.last_mean_score:.1f}, "
        f"best_eval={result.best_eval_score:.1f}, "
        f"policy_loss={result.last_policy_loss:.4f}\n"
        f"checkpoint: {result.checkpoint_path}"
    )
